/* ============================================
   THE LITTLE GREEN BOOK - Data
   Add new advisers or categories here.
   ============================================ */

const CATEGORIES = [
  { id: 'all', label: 'All Advisers' },
  { id: 'gps-general-practice', label: 'GPs & General Practice' },
  { id: 'neurology', label: 'Neurology' },
  { id: 'oncology', label: 'Oncology' },
  { id: 'geriatric-medicine', label: 'Geriatric Medicine' },
  { id: 'dementia-specialist', label: 'Dementia Specialist' },
  { id: 'surgeons', label: 'Surgeons' },
  { id: 'psychiatry', label: 'Psychiatry' },
];

const ADVISERS = [
  {
    name: 'Iona Cobb',
    organisation: 'The Sloane Street Surgery',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A trusted private GP at The Sloane Street Surgery, Dr Iona Cobb is known for her unhurried, intuitive consultations and her genuine attentiveness to patients with ongoing care needs and the families supporting them.',
    extendedBio: 'Dr Iona Cobb practises at The Sloane Street Surgery, one of London\'s most respected private GP practices. She is widely valued for her ability to manage the layered, long-term needs of patients living with chronic illness or requiring care at home - from polypharmacy review and cardiovascular risk management to coordinating with consultants, hospital teams and live-in carers. Iona\'s discreet, continuity-led approach is particularly reassuring for clients who depend on a single, dependable point of contact across an increasingly complex healthcare landscape.',
  },
  {
    name: 'Theo Criswell',
    organisation: 'Criswell Medical Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A partner at Criswell Medical Practice in Sloane Square, Dr Theo Criswell brings rigorous, evidence-based GP care to clients with complex medical needs and ongoing care arrangements.',
    extendedBio: 'Dr Theo Criswell practises at Criswell Medical Practice (Sloane Square, SW1W), one of central London\'s longest-established private GP groups. He is valued for his clarity, his thoroughness and his unwavering focus on getting the medical detail right - particularly important when patients are managing several chronic conditions, recovering from hospital stays or relying on professional care. Michael is known for his clear communication with families and carers and his commitment to keeping every aspect of a patient\'s care plan working together.',
  },
  {
    name: 'Paul Ettlinger',
    organisation: 'The London General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A founding partner of The London General Practice on Harley Street, Dr Paul Ettlinger is one of London\'s most trusted private GPs, known for the steady, hands-on support he gives clients and the families coordinating their care.',
    extendedBio: 'Dr Paul Ettlinger has been at the heart of The London General Practice for decades, building a reputation as a cornerstone GP for households managing chronic illness, recovery and complex care. His patients value his thoroughness, his willingness to make house calls, and his exceptional ability to translate complex medical issues into clear, calm guidance for patients, families and the carers around them. Paul\'s proactive, continuity-led approach makes him a genuine medical partner for any family seeking joined-up care.',
  },
  {
    name: 'Angela Rai',
    organisation: 'The London General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Angela Rai is one of London\'s leading private GPs and a recognised authority in longevity and preventative medicine.',
    extendedBio: 'As Medicines Management Lead at The London General Practice, Dr Rai brings a uniquely integrated approach to patient care - combining her dual specialisation in Cardiology and Anti-Ageing Medicine with a background in Psychology to deliver truly personalised, evidence-based medicine.',
  },
  {
    name: 'Simon Moore',
    organisation: 'Moore Medical Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'The founder of Moore Medical Practice on the Kings Road in Chelsea, Dr Simon Moore offers calm, authoritative private GP care to clients managing complex health and care arrangements.',
    extendedBio: 'Dr Simon Moore leads Moore Medical Practice in the heart of Chelsea (Kings Road, SW3), a private GP service known for its meticulous standards and continuity of care. Simon\'s clinical authority and steady judgement make him a natural choice for clients juggling multiple specialists, long-term conditions or live-in care. He is particularly valued for his thorough approach to diagnosis and treatment planning, and his close working relationships with consultants, families and professional carers.',
  },
  {
    name: 'Carolyn Barshall',
    organisation: 'Chelsea General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A long-established private GP at Chelsea General Practice on Lower Sloane Street, Dr Carolyn Barshall is known for her warm, personalised approach and her particular dedication to patients with ongoing care needs.',
    extendedBio: 'Dr Carolyn Barshall practises at Chelsea General Practice, and is regarded as one of the most attentive private GPs in the area. Her quietly devoted following among patients receiving long-term care reflects her unhurried consultations, careful attention to medication reviews, and genuine interest in the social and family context surrounding illness. Carolyn is particularly skilled at supporting patients through difficult transitions - bereavement, mobility loss, cognitive concerns - with continuity, compassion and discretion that work seamlessly alongside professional carers and family.',
  },
  {
    name: 'Tim Ladbrooke',
    organisation: 'Courtfield Private Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A senior partner at Courtfield Private Practice in South Kensington, Dr Tim Ladbrooke is widely respected for his patient-first private GP care and the support he offers clients with ongoing medical and care needs.',
    extendedBio: 'Dr Tim Ladbrooke practises at Courtfield Private Practice (South Kensington), where he is known for combining clinical thoroughness with a genuinely warm, attentive style. His patients particularly value his readiness to go the extra mile - house calls, careful medication oversight, direct communication with consultants and carers - when complex needs make medical life difficult to navigate alone. Tim\'s continuity-led approach is well-suited to households where a single trusted GP, working alongside a wider care team, makes all the difference.',
  },
  {
    name: 'Lucy Ansell',
    organisation: 'Linbury Doctors',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Lucy Ansell is a founding partner at Linbury Doctors, a small, highly personal private GP service conducting home visits for clients across the Cotswolds.',
    extendedBio: 'Lucy is known for a traditional, doctor-at-the-door style of medicine that is increasingly rare and especially valued by patients who wish to receive medical treatment in the comfort of their own homes. She combines unhurried home consultations with rigorous medical follow-through - coordinating specialist input, hospital admissions and at-home rehabilitation alongside carers and family - making her an exceptional choice for households seeking dignified, expert and continuous care.',
  },
  {
    name: 'Michael Criswell',
    organisation: 'Criswell Medical Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A founding figure at Criswell Medical Practice in Sloane Square, Dr Michael Criswell brings decades of experience as a private family doctor, with a long-standing reputation for supporting patients living with complex, ongoing care needs.',
    extendedBio: 'Dr Michael Criswell is one of the longest-serving private GPs in central London, based at Sloane Square (SW1W). His enduring relationships with patients - many spanning thirty years or more - are invaluable when continuity of care matters most: managing chronic illness, supporting recovery at home, or navigating the layered needs of someone receiving live-in care. Theo is admired for his old-school continuity of care, willingness to make house calls, and ability to handle the full breadth of medical concerns - from frailty and cognitive change to end-of-life planning - with quiet authority and warmth.',
  },
  {
    name: 'Toby Dean',
    organisation: 'The Sloane Street Surgery',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A trusted private GP at The Sloane Street Surgery, Dr Toby Dean is known for combining clinical rigour with a warm, accessible style that suits clients who rely on consistent medical support at home.',
    extendedBio: 'Dr Toby Dean practises at The Sloane Street Surgery, one of London\'s most respected private GP practices. He is valued for his approachable manner, his thoroughness, and his ability to make complex medical information clear and reassuring for patients and the families and carers supporting them. Toby\'s emphasis on preventative care and long-term wellbeing makes him an excellent partner for households managing chronic illness or planning ahead for a loved one\'s evolving care needs.',
  },
  {
    name: 'Charlie Middle',
    organisation: 'Wessex Private General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Charlie Middle is the founder of the Wessex Private General Practice, serving patients across Dorset, Somerset and Devon. With over three decades of clinical experience, Dr Middle leads the practice who are recognised for their ethos of \'modern medicine with traditional values\'',
    extendedBio: 'Dr Charlie Middle qualified from St Thomas\' Hospital, London in 1989 and has spent over three decades in general practice, including 26 years as a GP Partner in Dorset. His clinical interests include orthopaedic medicine, minor surgery, and mental health. He founded Wessex Private General practice in 2022 . He and his four experience GP colleagues hold clinics at The Poundbury Clinic, Dorchester and the Kingston Wing, Yeovil Hospital.',
  },
  {
    name: 'Simmy Kaur',
    organisation: 'The Nine Clinic',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A founding partner of The Nine Clinic, with sites on Harley Street and Sloane Square, Dr Simmy Kaur is widely recognised for her holistic, longevity-focused medicine - a particular draw for patients seeking to maintain wellbeing alongside complex care needs.',
    extendedBio: 'Dr Simmy Kaur practises at The Nine Clinic (Harley Street, W1 and Sloane Square, SW1W), a private GP and longevity-focused practice she founded. Simmy blends evidence-based general practice with preventative and lifestyle medicine - comprehensive screening, hormone health, bone density, cardiovascular and cognitive assessments - which aligns closely with the priorities of clients managing long-term conditions and seeking the best possible quality of life. She is respected for her warm, scientifically rigorous approach and is a strong choice for patients and families who want a proactive medical partner alongside their care arrangements.',
  },
  {
    name: 'Lucy Foster',
    organisation: 'Dr Fstr',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Lucy Foster is a private family doctor and founder of DR.FSTR an independent medical practice providing quality healthcare delivered at home with discretion and empathy.',
    extendedBio: 'Dr Lucy Foster founded DR.FSTR a private home-visiting medical practice providing medical care for individuals, families and estates. The practice has enhanced clinical oversight from an in-house Consultant Physician. The practice is deliberately small so that they can offer the highest standard of care, continuity and accessibility, visiting their patients at home 24/7/365. Their work is guided by empathy, discretion, and clinical excellence, with a strong focus on long-term doctor-patient relationships and careful coordination of care.',
  },
  {
    name: 'Amina Albeyatti',
    organisation: 'Family Doctor Group',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Amina Albeyatti is the Founder and Medical Director of Family Doctor Group, a leading private healthcare provider in Surrey offering GP, longevity and specialist medical services. She is known for delivering exceptional, personalised care and has earned a reputation for combining clinical excellence with a warm, compassionate approach.',
    extendedBio: 'With a special interest in preventative medicine, longevity and complex health conditions, Dr Albeyatti supports patients through every stage of their healthcare journey. From optimising long-term health and reducing disease risk to coordinating specialist opinions and navigating complex diagnoses, she provides trusted medical guidance and advocacy for individuals and families alike. Her commitment is to ensure every patient receives the right care, from the right specialist, at the right time.',
  },
  {
    name: 'Liza Osagie-Clouard',
    organisation: 'Solice Health',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Founder of SOLICE - the award-winning international concierge longevity and primary care practice serving principals and their families across London, Monaco and the United States. A physician with a background in surgery, regenerative science and precision medicine, Dr Osagie-Clouard is recognised internationally as a leading voice in modern longevity care, combining advanced diagnostics, preventative medicine and the highest standards of clinical judgement with a deeply personal, relationship-led approach.',
    extendedBio: 'Dr Liza Osagie-Clouard is the Founder of SOLICE, the award-winning international concierge medical practice delivering bespoke longevity and primary care to principals, families and offices across London, Monaco and the United States. Built around the belief that exceptional medicine should be proactive, continuous and profoundly personal, SOLICE today represents a new and globally connected model of private practice - one in which a single, trusted medical team accompanies its members across every chapter of life, every time zone, and every stage of health. Trained at Guy\'s Hospital and University College London, Dr Osagie-Clouard holds degrees in Medicine and Surgery and completed her PhD at the Royal National Orthopaedic Hospital, where her research investigated cellular ageing and bone regeneration. Following an award-winning orthopaedic surgical career across the United Kingdom and the United States, she moved into longevity and precision medicine - translating the science of regeneration, metabolic health and performance into a clinical practice designed for the realities of international life. Founded in 2020, SOLICE has become widely regarded as one of the most considered concierge practices of its generation, with members served seamlessly across continents by a discreet network of leading specialists, longevity scientists and allied practitioners. Dr Osagie-Clouard is known particularly for her clinical depth, her warmth, and her ability to translate the most sophisticated diagnostics into care that feels intelligent, intuitive and unhurried.',
  },
  {
    name: 'Tim Evans',
    organisation: 'Solice Health',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Medical Director of SOLICE - the award-winning international concierge longevity and primary care practice operating across London, Monaco and the United States. One of the United Kingdom\'s most respected private General Practitioners and former Apothecary to Her Majesty The Queen and the Royal Households of London, Dr Evans is widely regarded as one of London\'s most trusted physicians, known for his exceptional clinical judgement, discretion and a quietly integrative philosophy of care.',
    extendedBio: 'Dr Tim Evans is Medical Director of SOLICE, the award-winning international concierge longevity and primary care practice serving members across London, Monaco and the United States. With more than three decades in private medicine, he is known for the calibre of his clinical judgement, the depth of his patient relationships and a quietly integrative approach that places prevention, continuity and whole-person wellbeing at the centre of care. Dr Evans qualified from Westminster Hospital Medical School and trained across several of London\'s leading teaching hospitals before founding his own private practice in Fulham in 1990. He went on to establish Westover House and Grace Belgravia, pioneering one of the capital\'s earliest integrated private healthcare models - a thoughtful pairing of conventional medicine with lifestyle, nutritional and complementary disciplines that would, in time, become the template for much of modern London concierge practice. In 2003, Dr Evans was appointed Apothecary to Her Majesty The Queen and the Royal Households of London, later continuing the role for Their Majesties The King and Queen. Over nearly two decades, he provided discreet, high-standard medical care to members of the Royal Household - a role defined by continuity, confidentiality and the very highest standards of clinical practice. He has also served on the Medical Committee of King Edward VII Hospital and as a Council Member of the Chelsea Clinical Society. At SOLICE, Dr Evans brings together his depth of experience in family medicine, preventative healthcare and integrative practice to help shape a modern model of concierge medicine - one centred on longevity, continuity and care delivered with quiet excellence.',
  },
  {
    name: 'Andrew McIver MB ChB (Hons) MRCGP',
    organisation: 'Sloane Medical Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Providing highly personalised, continuity-led healthcare from the heart of Chelsea, Dr Andrew McIver is a trusted private GP with expertise in complex medical care, preventive health, and addiction medicine.',
    extendedBio: 'Dr McIver is a co-founder and Director of Sloane Medical Practice, an established private GP practice on Sloane Street. He cares for a longstanding UK and international patient base, with a particular focus on comprehensive medical assessment, complex case management, and the coordination of specialist care. A graduate of the University of Liverpool Medical School with Honours, he became a Member of the Royal College of General Practitioners in 2007. His broad hospital training has providing a strong foundation for managing complex and multi-system conditions. He has a recognised special interest in addiction medicine and works closely with multidisciplinary teams in the UK and internationally to support patients requiring specialist intervention and treatment. Known for his calm, approachable manner and attention to detail, he is valued for the continuity, discretion, and personalised care he provides. Dr McIver is regularly recognised in the Spear\'s 500 Private Doctors Index as a Top Recommended Practitioner.',
  },
  {
    name: 'Hugh Coyne',
    organisation: 'Coyne Medical',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A co-founder of Coyne Medical in West London, Dr Hugh Coyne is a private GP known for his warm, considered approach and his focus on early detection and prevention, helping busy people stay well through personalised health screening.',
    extendedBio: 'A co-founder of Coyne Medical in West London, Dr Hugh Coyne is a private GP known for his warm, considered approach and his focus on early detection and prevention, helping busy people stay well through personalised health screening.',
  },
  {
    name: 'Jason Reddy',
    organisation: '',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Jason Reddy - a GP with over 32 years experience in both the NHS and Private Sectors. He is currently Vice President of the Independent Doctors Federation and has 2 decades of clinical leadership experience. His skill is in realising commercial and professional relationships and facilitating momentum for forging ahead with mutual partnerships.',
    extendedBio: 'The core leadership traits and professional values driving Dr Reddy\'s career include: Youthful Energy: Drives a highly motivated, vibrant, and proactive approach to tackling complex projects and team dynamics. Courageous Circumspection: Combines bold, strategic risk-taking with cautious, careful analysis of potential outcomes. Winning Ways: Demonstrates a proven ability to inspire trust, build strong partnerships, and consistently deliver successful project outcomes. Balance: Maintains a well-rounded and objective perspective when making critical business or organizational decisions. Intuition: Utilizes sharp, experienced-backed insight to anticipate industry trends and confidently navigate ambiguous situations. Moral Fibre: Grounded in a strong sense of professional ethics, integrity, and personal accountability in all business dealings.',
  },
  {
    name: 'John O\'Dwyer',
    organisation: 'Mayo Clinic Healthcare London / HCA Healthcare',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'A consultant neurologist at The Mayo Clinic London and HCA\'s Lister Hospital, Dr John O\'Dwyer is an expert in holistic general neurology and medical care. Additionally, he has wide subspecialist knowledge, for complex disorders that need ongoing care.',
    extendedBio: 'Dr John O\'Dwyer is a senior consultant neurologist working at The Mayo Clinic London and The Lister Hospital (SW1W). His clinical interests - epilepsy, migraine and headache disorders, stroke and TIA, memory loss, Parkinson\'s disease and other movement disorders - sit at the heart of long-term neurological care. John is known for his careful, methodical assessments, his ability to translate complex investigations into clear guidance for patients and families, and his close collaboration with cardiology, psychiatry and rehabilitation teams. For anyone facing a new diagnosis or planning ongoing care for a loved one, he is a calm, authoritative presence who brings world-class expertise within reach',
  },
  {
    name: 'Ben Turner',
    organisation: 'HCA Healthcare UK',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'A senior consultant neurologist with HCA Healthcare UK at London Bridge and The Shard, Dr Ben Turner has a particular focus on neurological conditions that require sustained, multidisciplinary care, including Multiple Sclerosis Parkinson\'s disease and dementia.',
    extendedBio: 'Dr Ben Turner is a leading consultant neurologist practising within HCA Healthcare UK at London Bridge Hospital and The Shard for over 20 years. He has built a strong reputation for the assessment and long-term management of conditions that demand ongoing care - Multiple Sclerosis, Parkinson\'s disease, essential tremor, gait disturbance, memory disorders and the after-effects of stroke. Patients, families and care teams value his patient, methodical clinical style and his ability to coordinate ongoing care with neuro-rehabilitation, geriatric medicine and primary care, providing the integrated support that patients with chronic neurological disease so often need.',
  },
  {
    name: 'Emer MacSweeney',
    organisation: 'Re:Cognition Health',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'CEO and Medical Director of Re:Cognition Health, Dr Emer MacSweeney is a leading neuroradiologist and brain-health specialist at the forefront of memory and cognitive care.',
    extendedBio: 'Dr Emer MacSweeney founded Re:Cognition Health, and has built it into one of the UK\'s foremost private centres for the assessment and treatment of memory disorders, mild cognitive impairment and Alzheimer\'s disease - including access to leading clinical trials of disease-modifying therapies. For families noticing early changes in a loved one or supporting someone already living with dementia, Emer offers world-class diagnostic precision, clear guidance and a route into the most advanced treatments available, including Kisunla and leqembi, all delivered with vast experience and characteristic warmth and discretion.',
  },
  {
    name: 'Dominic Paviour',
    organisation: 'HCA Healthcare UK',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'A consultant neurologist who operates predominantly out of Welbeck Neurology. Dr Dominic Paviour specialises in Parkinson\'s disease and other movement disorders that require sustained, coordinated care.',
    extendedBio: 'Dr Dominic Paviour is a senior consultant neurologist. His specialist expertise in Parkinson\'s disease, dystonia, tremor and other movement disorders makes him particularly important for patients whose care arrangements depend on managing fluctuating symptoms over years. Dominic combines rigorous clinical assessment with a thoughtful, unhurried style - coordinating closely with primary care, geriatric medicine, neuro-rehabilitation and family carers to keep patients as well, as mobile and as independent as possible.',
  },
  {
    name: 'John Janssen',
    organisation: 'HCA Healthcare UK',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'A senior consultant neurologist with HCA Healthcare UK at Kings Road and Chiswick, Dr John Janssen brings calm authority and broad clinical experience to patients with neurological conditions requiring long-term care.',
    extendedBio: 'Dr John Janssen is a distinguished consultant neurologist working within HCA Healthcare UK. His extensive experience across the breadth of clinical neurology - stroke, headache, neurodegenerative disease, neuropathies - makes him a valued source of guidance for patients and families navigating difficult diagnoses. John is known for his methodical, accessible approach and his exceptional ability to coordinate care across specialists, primary care and the home, offering the steady, integrated medical oversight that complex neurological care so often requires.',
  },
  {
    name: 'Johnathan Chan',
    organisation: 'HCA Healthcare UK',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'Dr Chan is a highly qualified, London-trained consultant neurologist and dementia specialist with HCA Healthcare UK, who led the way in establishing London Bridge Hospital as one of the first centres in the UK to deliver the latest Amyloid Targeting Therapies for early Alzheimer\'s disease',
    extendedBio: 'Dr Chan led the way in establishing London Bridge Hospital as one of the first centres in the UK to deliver the latest Amyloid Targeting Therapies for the treatment of early Alzheimer\'s disease, giving patients new hope in combating this previously untreatable condition. Bringing together the most advanced diagnostic techniques in the field of memory and dementia assessment where he practises at The Shard, Dr Chan combines cutting-edge medicine with his bespoke, personalised and compassionate approach. He is known for his unique warmth and empathy, helping patients and their families find answers and navigate the complex challenges of this condition.',
  },
  {
    name: 'David Choluj',
    organisation: 'London Neurology Clinic',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'Dr David Choluj is a Consultant Neurologist and Medical Director of London Neurology Clinic, the first UK and first neurology practice outside the United States to receive the American Academy of Neurology (AAN) Neurology Practice Award. He specialises in cognitive disorders, headache disorders and migraine, Parkinson\'s disease, and other complex neurological conditions affecting older adults.',
    extendedBio: 'Known for his thorough and compassionate approach, David provides expert diagnostic assessments, second opinions and ongoing neurological care. He works closely with families, private GPs, therapists and care teams to coordinate bespoke care plans that support independence, wellbeing and quality of life.',
  },
  {
    name: 'Professor K Ray Chaudhuri',
    organisation: 'Kings College Hospital',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'Professor K. Ray Chaudhuri is Director of Research and Clinical Trials at Kings College Hospital, London and Dubai. Ex-Professor of Neurology/Movement Disorders at King\'s College Hospital and King\'s College London, and Ex-Director of the Parkinson Foundation International Centre of Excellence at King\'s College Hospital in London.',
    extendedBio: 'He is founder of MDS Nonmotor PD Study group (NMSG), Ex Chairman and now steering group of the Industry Engagement Committee, and Co Chair Task force of the Parkinson Wellness committee of the Movement Disorders Society (MDS) was a member of the MDS Congress Scientific Programme Committee (2013-2017) and is Founder -Editor-in-Chief of the njp Parkinson\'s Disease, and current Editor Front. Aging Neurosci. - Parkinson\'s Disease and Aging-related Movement Disorders and a founder member of Kings Parkinson\'s Charity. He is advisor to NHS England, General Medical Council as well as Parkinson\'s UK and Parkinson\'s Europe. Professor Chaudhuri is the author of over 600 articles (Scopus listed) , with H index > 100, co-editor of 7 books on Parkinson\'s disease and restless legs syndrome, and winner of the British Medical Association Book Awards commendation in 2015 and 2017. He is also the recipient of 2018 Jay Van Andel Award Outstanding Achievement in Parkinson\'s Disease Research (pioneering holistic assessments and non-motor subtypes), as well as National Institute for Health Research/Royal College of Physicians award for outstanding research leadership in 2017. He was elected honorary member of the Movement Disorders Society in 2021, Honorary Professor Brasov University and received the UK NHS Gold merit award in 2021 for excellence in research and clinical service. In 2023 he was featured as "role model" in British Medical Journal. He has been a guest lecturer worldwide, including in Japan, China, Taiwan, Vietnam, Thailand, Singapore, Australia, India, Africa, the US, Russia, and Europe. In 2025 he is ranked within the top 2% of all scientists in the world (Stanford and Elsevier ranking ) and in 2024, an independent review in Frontiers journal by LI et al rated KRC as the one with most publications globally in nonmotor Parkinson\'s since 2013 (Li et al , DOI 10.3389/fnagi.2024.1335550). He is a member of the Parkinson\'s UK project grants College of Experts member and reviewer of USA Congressionally Directed Medical Research Programs (U.S. Army Medical Research Acquisition Activity (USAMRAA) ) and NIH and Middle East grant programmes such as Dubai Health Authority and Saudi Arabia Grants Committee (RDIA grants programme).',
  },
  {
    name: 'Daniel Krell',
    organisation: 'HCA Healthcare UK',
    category: 'oncology',
    specialty: 'Oncology',
    bio: 'A consultant medical oncologist at HCA\'s Wellington Hospital in St John\'s Wood, as well as the Harley Street Clinic, and Leaders in Oncology Care (Harley Street). Dr Daniel Krell is recognised for his compassionate, individualised approach to cancer care for patients with complex care needs.',
    extendedBio: 'He is known for tailoring treatment intensity to the realities of each patient - balancing efficacy against tolerability, comorbidity and quality of life - which is invaluable when cancer treatment must sit alongside ongoing care, frailty or other long-term conditions. Daniel is praised by families and care teams for his clarity, patience and willingness to spend the time needed at every step, from diagnosis through treatment planning to survivorship and palliative care, making him a trusted partner for any patient facing a cancer diagnosis whilst receiving care.',
  },
  {
    name: 'Prashanth Reddy',
    organisation: 'HCA Concierge',
    category: 'geriatric-medicine',
    specialty: 'Geriatric Medicine',
    bio: 'As a highly experienced consultant neuro-geriatrician, Dr Prashanth Reddy specialises in the holistic medical oversight of patients with complex, multi-layered care needs across The Lister Hospital and London Bridge.',
    extendedBio: 'Dr Prashanth Reddy is a consultant in geriatric medicine, with bases at The Lister Hospital and London Bridge. His practice is built around the needs of patients living with frailty, multiple long-term conditions, or significant cognitive change - comprehensive medical assessment, falls prevention, dementia and delirium care, polypharmacy review, continence, bone health and end-of-life planning. Prashanth is widely respected for his ability to see the whole person, working closely with families and professional carers to design realistic care plans that preserve independence and dignity. For any patient with multiple, interacting conditions, he is a natural and invaluable point of expert oversight.',
  },
  {
    name: 'Iñaki Bovill',
    organisation: 'HCA Healthcare UK',
    category: 'geriatric-medicine',
    specialty: 'Geriatric Medicine',
    bio: 'Dr Iñaki Bovill is a leading elderly care and general medicine doctor based in London. With over 25 years of experience, Dr Bovill is highly experienced in a wide range of treatments, with his areas of expertise including peri-operative medicine, continence, complex elderly medicine, rehabilitation, polypharmacy and geriatric medicine.',
    extendedBio: 'Dr Iñaki Bovill is a respected consultant in geriatric medicine practising across both NHS and private settings. His practice is built around the realities of caring for patients with multiple, interacting conditions - comprehensive assessment, falls and frailty management, dementia and delirium care, polypharmacy review and rehabilitation. Iñaki is valued for his attention to detail and his commitment to working closely with families, primary care and professional carers to design care plans that genuinely sustain quality of life at home.',
  },
  {
    name: 'Shahbaz Roshan',
    organisation: 'HCA Healthcare UK',
    category: 'geriatric-medicine',
    specialty: 'Geriatric Medicine',
    bio: 'A consultant in geriatric medicine, Dr Shahbaz Roshan takes a holistic, person-centred approach to clients living with frailty and multiple long-term conditions.',
    extendedBio: 'Dr Roshan is a respected consultant geriatrician based across multiple London hospitals. His practice is built around the medical realities of patients receiving care - managing frailty, falls, polypharmacy, cognitive change and the interplay of multiple chronic conditions. Shahbaz is particularly valued for his ability to address the physical and emotional dimensions of care together, working closely with families and professional carers to design realistic, dignity-preserving plans that hold up over time.',
  },
  {
    name: 'Prof. June Andrews OBE',
    organisation: 'Independent / National',
    category: 'dementia-specialist',
    specialty: 'Dementia Specialist',
    bio: 'One of the UK\'s most influential voices on dementia care, Prof. June Andrews OBE is an independent specialist whose practical guidance has shaped how families, professionals and care providers support people living with dementia.',
    extendedBio: 'Professor June Andrews OBE is a nationally recognised dementia specialist, author of Dementia: The One-Stop Guide and former director of the Dementia Services Development Centre at the University of Stirling. She advises families, care providers and institutions across the UK on every aspect of dementia - from early diagnosis and home adaptation to choosing care settings, briefing live-in carers, managing behavioural changes and navigating the legal and financial implications. June\'s independence, clarity and deep practical knowledge make her uniquely placed to help clients and families plan ahead, avoid common pitfalls and secure the best possible quality of life through the journey of dementia.',
  },
  {
    name: 'Vanash Patel',
    organisation: 'Private Practice',
    category: 'surgeons',
    specialty: 'Colorectal Surgeon',
    bio: 'Vanash Patel is a Consultant Colorectal and General Surgeon at West Hertfordshire Teaching Hospitals NHS Trust and an Honorary Clinical Associate Professor at Imperial College London.',
    extendedBio: 'He specialises in the management of colorectal cancer, benign colorectal conditions, abdominal wall hernias and advanced endoscopic disorders. He is recognised nationally for his work in robotic surgery, digital healthcare innovation and enhanced recovery pathways. Mr Patel leads one of the UK\'s highest-volume robotic colorectal surgery programmes and has pioneered integrated pathways combining robotic surgery, digital prehabilitation and virtual hospital care to improve patient outcomes and recovery. He has published extensively in colorectal surgery, robotic surgery and healthcare innovation, and is actively involved in research, education and service development. He supports adults requiring specialist colorectal and general surgical assessment, including patients seeking expert second opinions, management of colorectal cancer, diverticular disease, inflammatory bowel disease, pelvic floor disorders, hernias and complex benign colorectal conditions. He is committed to delivering highly personalised, patient-centred care using the latest evidence-based and minimally invasive techniques. Places of Work West Hertfordshire Teaching Hospitals NHS Trust (Watford General Hospital and St Albans City Hospital) Imperial College London (Honorary Clinical Associate Professor) Spire Bushey Hospital The Wellington Hospital Cleveland Clinic London',
  },
  {
    name: 'Lawrence Okiror',
    organisation: 'HCA Healthcare UK',
    category: 'surgeons',
    specialty: 'Consultant Thoracic and Robotic Surgeon',
    bio: 'Mr Lawrence Okiror is a consultant thoracic and robotic surgeon at London Bridge Hospital and The Lister Hospital, Chelsea, and leads the interventional airway service at Guy\'s and St Thomas\'',
    extendedBio: 'Alongside lung cancer and emphysema surgery, much of his work is relieving chest symptoms in older patients and advanced disease - breathlessness from fluid around the lung or a narrowed airway, pain, persistent cough - often through minor procedures under, including indwelling drains managed at home. He works alongside palliative-care and home-care teams, judges fitness for surgery on biology rather than birthdays, and says plainly when no procedure is the right answer. Enquiries from families are welcome.',
  },
  {
    name: 'Sarah Alsawy-Davies',
    organisation: 'Auctoritas Advisory',
    category: 'psychiatry',
    specialty: 'Psychiatry',
    bio: 'Multi-award winning Dr Sarah Alsawy is a leading expert psychologist, specialising in the field of human relationships, re-wiring dynamics to create healthy and fulfilling interactions. With over 15 years of experience, her approaches create long- term changes that improve resilience, confidence, and wellbeing.',
    extendedBio: 'Dr Sarah Alsawy is a multi-award winning expert clinical psychologist, specialist in the field of relationships, family dynamics, and emotional resilience. Her Relational Alignment Protocol is an innovative, evidence-based framework that helps clients transform conflict, disconnection, and emotional distress into safety, trust, and wellbeing. With over 15 years of clinical experience, her clients experience strengthened relationships, improved communication, and increased confidence. Working with executive couples and families, her work is particularly important during significant life transitions, including marriage or separation, addition of new family members, succession planning, and liquidity events.',
  },
];
