/* ============================================
   THE LITTLE GREEN BOOK - Data
   Add new advisers or categories here.
   ============================================ */

const CATEGORIES = [
  { id: 'all', label: 'All Advisers' },
  { id: 'gps-general-practice', label: 'GPs & General Practice' },
  { id: 'neurology', label: 'Neurology' },
  { id: 'oncology', label: 'Oncology' },
  { id: 'rheumatology', label: 'Rheumatology' },
  { id: 'geriatric-medicine', label: 'Geriatric Medicine' },
  { id: 'dementia-specialist', label: 'Dementia Specialist' },
  { id: 'surgeons', label: 'Surgeons' },
  { id: 'ear-nose-throat', label: 'Ear, Nose and Throat' },
  { id: 'ophthalmology', label: 'Ophthalmology' },
  { id: 'psychiatry', label: 'Psychiatry' },
  { id: 'exercise-rehab', label: 'Exercise and Rehabilitation' },
  { id: 'residential', label: 'Residential Care' },
];

const ADVISERS = [
  {
    name: 'Iona Cobb',
    organisation: 'The Sloane Street Surgery',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A trusted private GP at The Sloane Street Surgery, Dr Iona Cobb is known for her unhurried, intuitive consultations and her genuine attentiveness to patients with ongoing care needs and the families supporting them.',
    extendedBio: 'Dr Iona Cobb practises at The Sloane Street Surgery, one of London\'s most respected private GP practices. She is widely valued for her ability to manage the layered, long-term needs of patients living with chronic illness or requiring care at home - from polypharmacy review and cardiovascular risk management to coordinating with consultants, hospital teams and live-in carers. Iona\'s discreet, continuity-led approach is particularly reassuring for clients who depend on a single, dependable point of contact across an increasingly complex healthcare landscape.',
  },
  {
    name: 'Theo Criswell',
    organisation: 'Criswell Medical Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A partner at Criswell Medical Practice in Sloane Square, Dr Theo Criswell brings rigorous, evidence-based GP care to clients with complex medical needs and ongoing care arrangements.',
    extendedBio: 'Dr Theo Criswell practises at Criswell Medical Practice (Sloane Square, SW1W), one of central London\'s longest-established private GP groups. He is valued for his clarity, his thoroughness and his unwavering focus on getting the medical detail right - particularly important when patients are managing several chronic conditions, recovering from hospital stays or relying on professional care. Michael is known for his clear communication with families and carers and his commitment to keeping every aspect of a patient\'s care plan working together.',
  },
  {
    name: 'Paul Ettlinger',
    organisation: 'The London General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A founding partner of The London General Practice on Harley Street, Dr Paul Ettlinger is one of London\'s most trusted private GPs, known for the steady, hands-on support he gives clients and the families coordinating their care.',
    extendedBio: 'Dr Paul Ettlinger has been at the heart of The London General Practice for decades, building a reputation as a cornerstone GP for households managing chronic illness, recovery and complex care. His patients value his thoroughness, his willingness to make house calls, and his exceptional ability to translate complex medical issues into clear, calm guidance for patients, families and the carers around them. Paul\'s proactive, continuity-led approach makes him a genuine medical partner for any family seeking joined-up care.',
  },
  {
    name: 'Angela Rai',
    organisation: 'The London General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Angela Rai is one of London\'s leading private GPs and a recognised authority in longevity and preventative medicine.',
    extendedBio: 'As Medicines Management Lead at The London General Practice, Dr Rai brings a uniquely integrated approach to patient care - combining her dual specialisation in Cardiology and Anti-Ageing Medicine with a background in Psychology to deliver truly personalised, evidence-based medicine.',
  },
  {
    name: 'Simon Moore',
    organisation: 'Moore Medical Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'The founder of Moore Medical Practice on the Kings Road in Chelsea, Dr Simon Moore offers calm, authoritative private GP care to clients managing complex health and care arrangements.',
    extendedBio: 'Dr Simon Moore leads Moore Medical Practice in the heart of Chelsea (Kings Road, SW3), a private GP service known for its meticulous standards and continuity of care. Simon\'s clinical authority and steady judgement make him a natural choice for clients juggling multiple specialists, long-term conditions or live-in care. He is particularly valued for his thorough approach to diagnosis and treatment planning, and his close working relationships with consultants, families and professional carers.',
  },
  {
    name: 'Carolyn Barshall',
    organisation: 'Chelsea General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A long-established private GP at Chelsea General Practice on Lower Sloane Street, Dr Carolyn Barshall is known for her warm, personalised approach and her particular dedication to patients with ongoing care needs.',
    extendedBio: 'Dr Carolyn Barshall practises at Chelsea General Practice, and is regarded as one of the most attentive private GPs in the area. Her quietly devoted following among patients receiving long-term care reflects her unhurried consultations, careful attention to medication reviews, and genuine interest in the social and family context surrounding illness. Carolyn is particularly skilled at supporting patients through difficult transitions - bereavement, mobility loss, cognitive concerns - with continuity, compassion and discretion that work seamlessly alongside professional carers and family.',
  },
  {
    name: 'Tim Ladbrooke',
    organisation: 'Courtfield Private Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A senior partner at Courtfield Private Practice in South Kensington, Dr Tim Ladbrooke is widely respected for his patient-first private GP care and the support he offers clients with ongoing medical and care needs.',
    extendedBio: 'Dr Tim Ladbrooke practises at Courtfield Private Practice (South Kensington), where he is known for combining clinical thoroughness with a genuinely warm, attentive style. His patients particularly value his readiness to go the extra mile - house calls, careful medication oversight, direct communication with consultants and carers - when complex needs make medical life difficult to navigate alone. Tim\'s continuity-led approach is well-suited to households where a single trusted GP, working alongside a wider care team, makes all the difference.',
  },
  {
    name: 'Lucy Ansell',
    organisation: 'Linbury Doctors',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Lucy Ansell is a founding partner at Linbury Doctors, a small, highly personal private GP service conducting home visits for clients across the Cotswolds.',
    extendedBio: 'Lucy is known for a traditional, doctor-at-the-door style of medicine that is increasingly rare and especially valued by patients who wish to receive medical treatment in the comfort of their own homes. She combines unhurried home consultations with rigorous medical follow-through - coordinating specialist input, hospital admissions and at-home rehabilitation alongside carers and family - making her an exceptional choice for households seeking dignified, expert and continuous care.',
  },
  {
    name: 'Michael Criswell',
    organisation: 'Criswell Medical Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A founding figure at Criswell Medical Practice in Sloane Square, Dr Michael Criswell brings decades of experience as a private family doctor, with a long-standing reputation for supporting patients living with complex, ongoing care needs.',
    extendedBio: 'Dr Michael Criswell is one of the longest-serving private GPs in central London, based at Sloane Square (SW1W). His enduring relationships with patients - many spanning thirty years or more - are invaluable when continuity of care matters most: managing chronic illness, supporting recovery at home, or navigating the layered needs of someone receiving live-in care. Theo is admired for his old-school continuity of care, willingness to make house calls, and ability to handle the full breadth of medical concerns - from frailty and cognitive change to end-of-life planning - with quiet authority and warmth.',
  },
  {
    name: 'Toby Dean',
    organisation: 'The Sloane Street Surgery',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A trusted private GP at The Sloane Street Surgery, Dr Toby Dean is known for combining clinical rigour with a warm, accessible style that suits clients who rely on consistent medical support at home.',
    extendedBio: 'Dr Toby Dean practises at The Sloane Street Surgery, one of London\'s most respected private GP practices. He is valued for his approachable manner, his thoroughness, and his ability to make complex medical information clear and reassuring for patients and the families and carers supporting them. Toby\'s emphasis on preventative care and long-term wellbeing makes him an excellent partner for households managing chronic illness or planning ahead for a loved one\'s evolving care needs.',
  },
  {
    name: 'Charlie Middle',
    organisation: 'Wessex Private General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Charlie Middle is the founder of the Wessex Private General Practice, serving patients across Dorset, Somerset and Devon. With over three decades of clinical experience, Dr Middle leads the practice who are recognised for their ethos of \'modern medicine with traditional values\'',
    extendedBio: 'Dr Charlie Middle qualified from St Thomas\' Hospital, London in 1989 and has spent over three decades in general practice, including 26 years as a GP Partner in Dorset. His clinical interests include orthopaedic medicine, minor surgery, and mental health. He founded Wessex Private General practice in 2022 . He and his four experience GP colleagues hold clinics at The Poundbury Clinic, Dorchester and the Kingston Wing, Yeovil Hospital.',
  },
  {
    name: 'Simmy Kaur',
    organisation: 'The Nine Clinic',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A founding partner of The Nine Clinic, with sites on Harley Street and Sloane Square, Dr Simmy Kaur is widely recognised for her holistic, longevity-focused medicine - a particular draw for patients seeking to maintain wellbeing alongside complex care needs.',
    extendedBio: 'Dr Simmy Kaur practises at The Nine Clinic (Harley Street, W1 and Sloane Square, SW1W), a private GP and longevity-focused practice she founded. Simmy blends evidence-based general practice with preventative and lifestyle medicine - comprehensive screening, hormone health, bone density, cardiovascular and cognitive assessments - which aligns closely with the priorities of clients managing long-term conditions and seeking the best possible quality of life. She is respected for her warm, scientifically rigorous approach and is a strong choice for patients and families who want a proactive medical partner alongside their care arrangements.',
  },
  {
    name: 'Lucy Foster',
    organisation: 'Dr Fstr',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Lucy Foster is a private family doctor and founder of DR.FSTR an independent medical practice providing quality healthcare delivered at home with discretion and empathy.',
    extendedBio: 'Dr Lucy Foster founded DR.FSTR a private home-visiting medical practice providing medical care for individuals, families and estates. The practice has enhanced clinical oversight from an in-house Consultant Physician. The practice is deliberately small so that they can offer the highest standard of care, continuity and accessibility, visiting their patients at home 24/7/365. Their work is guided by empathy, discretion, and clinical excellence, with a strong focus on long-term doctor-patient relationships and careful coordination of care.',
  },
  {
    name: 'Amina Albeyatti',
    organisation: 'Family Doctor Group',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Amina Albeyatti is the Founder and Medical Director of Family Doctor Group, a leading private healthcare provider in Surrey offering GP, longevity and specialist medical services. She is known for delivering exceptional, personalised care and has earned a reputation for combining clinical excellence with a warm, compassionate approach.',
    extendedBio: 'With a special interest in preventative medicine, longevity and complex health conditions, Dr Albeyatti supports patients through every stage of their healthcare journey. From optimising long-term health and reducing disease risk to coordinating specialist opinions and navigating complex diagnoses, she provides trusted medical guidance and advocacy for individuals and families alike. Her commitment is to ensure every patient receives the right care, from the right specialist, at the right time.',
  },
  {
    name: 'Liza Osagie-Clouard',
    organisation: 'Solice Health',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Founder of SOLICE - the award-winning international concierge longevity and primary care practice serving principals and their families across London, Monaco and the United States. A physician with a background in surgery, regenerative science and precision medicine, Dr Osagie-Clouard is recognised internationally as a leading voice in modern longevity care, combining advanced diagnostics, preventative medicine and the highest standards of clinical judgement with a deeply personal, relationship-led approach.',
    extendedBio: 'Dr Liza Osagie-Clouard is the Founder of SOLICE, the award-winning international concierge medical practice delivering bespoke longevity and primary care to principals, families and offices across London, Monaco and the United States. Built around the belief that exceptional medicine should be proactive, continuous and profoundly personal, SOLICE today represents a new and globally connected model of private practice - one in which a single, trusted medical team accompanies its members across every chapter of life, every time zone, and every stage of health. Trained at Guy\'s Hospital and University College London, Dr Osagie-Clouard holds degrees in Medicine and Surgery and completed her PhD at the Royal National Orthopaedic Hospital, where her research investigated cellular ageing and bone regeneration. Following an award-winning orthopaedic surgical career across the United Kingdom and the United States, she moved into longevity and precision medicine - translating the science of regeneration, metabolic health and performance into a clinical practice designed for the realities of international life. Founded in 2020, SOLICE has become widely regarded as one of the most considered concierge practices of its generation, with members served seamlessly across continents by a discreet network of leading specialists, longevity scientists and allied practitioners. Dr Osagie-Clouard is known particularly for her clinical depth, her warmth, and her ability to translate the most sophisticated diagnostics into care that feels intelligent, intuitive and unhurried.',
  },
  {
    name: 'Tim Evans',
    organisation: 'Solice Health',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Medical Director of SOLICE - the award-winning international concierge longevity and primary care practice operating across London, Monaco and the United States. One of the United Kingdom\'s most respected private General Practitioners and former Apothecary to Her Majesty The Queen and the Royal Households of London, Dr Evans is widely regarded as one of London\'s most trusted physicians, known for his exceptional clinical judgement, discretion and a quietly integrative philosophy of care.',
    extendedBio: 'Dr Tim Evans is Medical Director of SOLICE, the award-winning international concierge longevity and primary care practice serving members across London, Monaco and the United States. With more than three decades in private medicine, he is known for the calibre of his clinical judgement, the depth of his patient relationships and a quietly integrative approach that places prevention, continuity and whole-person wellbeing at the centre of care. Dr Evans qualified from Westminster Hospital Medical School and trained across several of London\'s leading teaching hospitals before founding his own private practice in Fulham in 1990. He went on to establish Westover House and Grace Belgravia, pioneering one of the capital\'s earliest integrated private healthcare models - a thoughtful pairing of conventional medicine with lifestyle, nutritional and complementary disciplines that would, in time, become the template for much of modern London concierge practice. In 2003, Dr Evans was appointed Apothecary to Her Majesty The Queen and the Royal Households of London, later continuing the role for Their Majesties The King and Queen. Over nearly two decades, he provided discreet, high-standard medical care to members of the Royal Household - a role defined by continuity, confidentiality and the very highest standards of clinical practice. He has also served on the Medical Committee of King Edward VII Hospital and as a Council Member of the Chelsea Clinical Society. At SOLICE, Dr Evans brings together his depth of experience in family medicine, preventative healthcare and integrative practice to help shape a modern model of concierge medicine - one centred on longevity, continuity and care delivered with quiet excellence.',
  },
  {
    name: 'Andrew McIver MB ChB (Hons) MRCGP',
    organisation: 'Sloane Medical Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Providing highly personalised, continuity-led healthcare from the heart of Chelsea, Dr Andrew McIver is a trusted private GP with expertise in complex medical care, preventive health, and addiction medicine.',
    extendedBio: 'Dr McIver is a co-founder and Director of Sloane Medical Practice, an established private GP practice on Sloane Street. He cares for a longstanding UK and international patient base, with a particular focus on comprehensive medical assessment, complex case management, and the coordination of specialist care. A graduate of the University of Liverpool Medical School with Honours, he became a Member of the Royal College of General Practitioners in 2007. His broad hospital training has providing a strong foundation for managing complex and multi-system conditions. He has a recognised special interest in addiction medicine and works closely with multidisciplinary teams in the UK and internationally to support patients requiring specialist intervention and treatment. Known for his calm, approachable manner and attention to detail, he is valued for the continuity, discretion, and personalised care he provides. Dr McIver is regularly recognised in the Spear\'s 500 Private Doctors Index as a Top Recommended Practitioner.',
  },
  {
    name: 'Hugh Coyne',
    organisation: 'Coyne Medical',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'A co-founder of Coyne Medical in West London, Dr Hugh Coyne is a private GP known for his warm, considered approach and his focus on early detection and prevention, helping busy people stay well through personalised health screening.',
    extendedBio: 'A co-founder of Coyne Medical in West London, Dr Hugh Coyne is a private GP known for his warm, considered approach and his focus on early detection and prevention, helping busy people stay well through personalised health screening.',
  },
  {
    name: 'Jason Reddy',
    organisation: '',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Jason Reddy - a GP with over 32 years experience in both the NHS and Private Sectors. He is currently Vice President of the Independent Doctors Federation and has 2 decades of clinical leadership experience. His skill is in realising commercial and professional relationships and facilitating momentum for forging ahead with mutual partnerships.',
    extendedBio: 'The core leadership traits and professional values driving Dr Reddy\'s career include: Youthful Energy: Drives a highly motivated, vibrant, and proactive approach to tackling complex projects and team dynamics. Courageous Circumspection: Combines bold, strategic risk-taking with cautious, careful analysis of potential outcomes. Winning Ways: Demonstrates a proven ability to inspire trust, build strong partnerships, and consistently deliver successful project outcomes. Balance: Maintains a well-rounded and objective perspective when making critical business or organizational decisions. Intuition: Utilizes sharp, experienced-backed insight to anticipate industry trends and confidently navigate ambiguous situations. Moral Fibre: Grounded in a strong sense of professional ethics, integrity, and personal accountability in all business dealings.',
  },
  {
    name: 'Nithya Nahappan',
    organisation: 'Maison Medica',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Nithya Nahappan is a highly experienced private GP providing personalised, concierge-level care for international families, professionals and students across London and Surrey. She is known for her strong patient advocacy, offering unhurried, continuity-driven care through premium clinics and bespoke home visits. Her holistic, thoughtful approach focuses on clarity, discretion and care tailored to each individual.',
    extendedBio: 'Dr Nithya Nahappan is a highly experienced private GP providing personalised, concierge-level medical care for international families, professionals and students in London and Surrey. She is recognised for her strong patient advocacy, ensuring individuals and families are guided and supported throughout every stage of their care. Her approach is unhurried and continuity-driven, combining access to premium clinic settings with bespoke home visiting services. With over 17 years of international clinical experience, Dr Nahappan adopts a holistic and thoughtful approach, supporting patients across all stages of life - from paediatric and family medicine to complex chronic conditions, mental illness and preventive care. Her practice is centred on clarity, discretion and long-term health optimisation, with an emphasis on understanding each patient\'s unique context and needs.',
  },
  {
    name: 'Sabrina Pao',
    organisation: 'Sloane Medical Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Sabrina Pao co-founded Sloane Medical Practice in 2010 and has over 20 years\' experience caring for patients across London. Known for her thorough, holistic approach, she takes time to understand the wider factors affecting health and is particularly experienced in women\'s health, preventative medicine, elderly care and complex diagnostic cases. Patients value her thoughtful, reassuring manner and the continuity of care she provides to individuals and families.',
    extendedBio: 'Dr Sabrina Pao co-founded Sloane Medical Practice in 2010 and has over 20 years\' experience caring for patients across London. She is known for her thorough, thoughtful and holistic approach to medicine, building long-term relationships with patients and families and often caring for multiple generations within the same family. After qualifying from Guy\'s, King\'s and St Thomas\' Medical School in 2003, she gained extensive hospital experience across paediatrics, psychiatry, general medicine and accident & emergency before completing her GP training in London and becoming a Member of the Royal College of General Practitioners in 2007. She also holds postgraduate qualifications in Family Planning and Occupational Health, together with a BSc in Management from Imperial College London. Dr Pao believes that good medical care begins with understanding the wider picture. She takes time to listen carefully and considers the many factors that influence health and wellbeing, including lifestyle, nutrition, sleep, stress, work and family life. Patients value her calm, reassuring manner, attention to detail and ability to bring clarity to complex or longstanding health concerns. Her clinical interests include women\'s health, supporting patients through different stages of life from contraception and family planning to perimenopause and menopause, as well as preventative medicine, health screening and weight management. She has a particular interest in caring for older patients, including providing home visits where appropriate, and enjoys working through challenging diagnostic problems to develop practical, personalised treatment plans. Alongside her clinical practice, Dr Pao is an experienced Occupational Health Physician, advising organisations ranging from private members\' clubs to multinational corporations on workplace health, fitness for work and return-to-work planning. Dr Pao lives in southwest London with her family, including her three sons. She is a member of the Independent Doctors Federation and the Chelsea Clinical Society',
  },
  {
    name: 'Elise Dallas',
    organisation: 'London General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Elise Dallas is a GP and Advanced British Menopause Society (BMS) Menopause Specialist with over 22 years of clinical experience. She holds several postgraduate diplomas in Obstetrics and Gynaecology and Sexual and Reproductive Health, reflecting her longstanding commitment to women\'s health throughout every stage of life. She is passionate about helping women navigate midlife with confidence, offering highly personalised, evidence-based care that looks beyond hormones alone.',
    extendedBio: 'Dr Dallas has a particular interest in supporting women whose menopause journey is more complex. She manages some of the most challenging menopause cases, including women with a history of breast cancer and other hormone-sensitive cancers, premature ovarian insufficiency (early menopause), endometriosis, significant medical conditions, persistent symptoms despite standard treatments, abnormal bleeding, and women who may benefit from testosterone therapy. To support these patients, she has developed a specialist Complex Menopause Service, working closely with a multidisciplinary network of experts, including oncologists, breast surgeons, rheumatologists, psychologists and bone health specialists, to provide comprehensive, joined-up care. What makes Dr Dallas\'s approach different is her belief that menopause is not simply about replacing hormones. Through the menopause and midlife services she has developed at The London General Practice and the Women\'s Health Centre, she delivers compassionate, personalised, evidence-based care that addresses every aspect of a woman\'s health during midlife. Known for her warm, patient-centred approach, Dr Dallas takes time to understand each woman\'s individual symptoms, concerns and health goals. Her consultations focus not only on managing menopausal symptoms but also on optimising long-term health, including bone, cardiovascular and metabolic health, weight management, sleep, cognitive function, mental wellbeing, sexual health and lifestyle factors. Having also developed the practice\'s weight management service, she combines nutritional, lifestyle and medical approaches, including weight-loss medications where appropriate, to support sustainable health outcomes. Treatment plans are tailored to each individual and may include hormonal and non-hormonal therapies, lifestyle interventions and specialist referrals when needed. Prior to her current roles, Dr Dallas spent over a decade as a Partner in an NHS practice, where she led Women\'s Health and Family Planning services. She later became Global Women\'s Health Lead at Babylon Health, overseeing the development of services spanning contraception, fertility, pregnancy, postnatal care and menopause. An advocate for better women\'s healthcare, Dr Dallas regularly contributes to national media, health publications, webinars, podcasts, educational events and through her own social media platforms, where she shares evidence-based information on menopause, midlife health and healthy ageing. She is the resident doctor for Chat magazine and a recognised voice in women\'s health and menopause, with expert commentary featured in RED, Stylist, The Times, The Daily Mail, The Telegraph, Women\'s Health and other leading national publications. She has also contributed expert clinical insights to several books, including Food for Menopause and Life After Weight-Loss Medication by Dr Linia Patel, as well as Menowars by Fiona Clark, contributing to discussions around bone health and healthy ageing in midlife women. As an ambassador and educator for the Menopause Research and Education Fund (MREF), Dr Dallas helps deliver evidence-based education to healthcare professionals around the world on menopause care, midlife health and the appropriate use of weight-loss medications, supporting improved standards of care for women internationally. Her mission is simple: to help women not only manage their menopause symptoms, but optimise their long-term health, wellbeing and quality of life through expert, compassionate and truly comprehensive midlife care.',
  },
  {
    name: 'Marcus Marquardt',
    organisation: 'London General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Marcus Marquardt is an experienced General Practitioner and Primary Care Doctor, having completed his State Examination in Germany. He is a dedicated and patient-focused clinician with a broad scope of expertise across general practice and preventative healthcare. Dr Marquardt is a member of the Royal College of General Practitioners and the Independent Doctors Federation, reflecting his commitment to maintaining high clinical standards and delivering quality care.',
    extendedBio: 'He provides a comprehensive range of GP services, including general medical consultations, skin disease assessment, women\'s and men\'s health, pregnancy and postnatal care, and sexual health and contraception. His practice also covers routine and travel vaccinations, childhood immunisations, paediatrics, and prescription services. In addition, Dr Marquardt offers home visits, ensuring accessible and continuous care for his patients. Known for his thorough and attentive approach, Dr Marquardt is committed to delivering personalised, holistic care tailored to each patient\'s individual needs.',
  },
  {
    name: 'Sanjay Mehta',
    organisation: 'London General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Sanjay Mehta graduated from Imperial College London in 2013 and has completed a further Bachelor of Science degree in Haematology. He has since been accredited as a Member of the Royal College of General Practitioners and a Diplomate of the Royal College of Obstetricians and Gynaecologists.',
    extendedBio: 'Dr Mehta has worked in both NHS Oxford and Cambridge University Hospitals, covering several medical, psychiatric and surgical specialties. He has also worked in NHS GP practices in both London and Oxford and more recently in COVID hubs during the pandemic. In addition, he has worked for a leading private online consultation platform. Dr Mehta has a particular interest in Paediatrics, having completed a Diploma of Child Health from the Royal College of Paediatrics & Child Health. He has also jointly published original research in the Archives of Disease in Childhood during a paediatric post at The John Radcliffe Hospital, Oxford and presented the findings at a national conference at Somerville College, University of Oxford. In 2021, Dr Mehta was appointed as Specialist Advisor for the Care Quality Commission (CQC), advising on Primary Medical Services and Integrated Care. His additional positions also include Medical Examiner for the General Medical Council (GMC).',
  },
  {
    name: 'Natalia Bogatcheva',
    organisation: 'London General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Natalia Bogatcheva graduated from University College London School of Medicine in 2003. After graduating, she went on to obtain extensive experience in Emergency Medicine, Oncology and Haematology. Dr Bogatcheva then completed her GP training at Guy\'s and St Thomas\' GP scheme, having worked in General Medicine, Stroke and Geriatric specialties.',
    extendedBio: 'Dr Bogatcheva has experience in both NHS and private practice, gaining a wealth of expertise while working in a very busy inner-city NHS practice between 2010 and 2016, and continuing her NHS work in an Urgent Care Centre at Guy\'s and St Thomas\' Hospital. She has a special interest in managing complex cases and in bringing together multidisciplinary teams to deliver coordinated, patient-centred care. Dr Bogatcheva is much loved by her patients and is known for her deeply compassionate approach. She takes great care to listen and understand each individual, and is highly regarded for her warm, attentive bedside manner and commitment to delivering truly personalised care.',
  },
  {
    name: 'Catrin Bevan',
    organisation: 'London General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Catrin Bevan has been a registered doctor for nearly 35 years and originally qualified from St. Bartholomew\'s medical school in 1985. She has worked as a General Practitioner for over 30 years, most of which has been in the UK.',
    extendedBio: 'In addition to her work in the UK Dr Bevan has also worked in the American hospital in Paris, the Middle East and in Poland for the Red Cross. She was also an emergency doctor and worked in private General practice in Bermuda. From 1999 to 2013 she was a Principle in a large NHS general practice in Surrey. Her particular specialities are inter alia women\'s health including teenage problems, contraception, the menopause and psychosexual counselling. Geriatric care and counselling for mental health issues are also key interests.',
  },
  {
    name: 'Sam Bennett',
    organisation: 'London General Practice',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Sam Bennett is an experienced General Practitioner at The London General Practice, where he also serves as Information Governance Lead. He qualified in medicine at the University of Wales College of Medicine and began his career with basic surgical training in South Wales, before progressing to specialist orthopaedic training in London to Registrar level. He subsequently transitioned into General Practice, bringing with him a strong foundation in musculoskeletal medicine.',
    extendedBio: 'Dr Bennett has worked extensively across both the NHS and private sector, including roles in an NHS practice in Hampton Court and as a GP with BUPA, before moving into full-time private practice on Harley Street. He has particular clinical interests in musculoskeletal and occupational medicine and is a certified Aviation Medical Examiner for the UK Civil Aviation Authority. His broad experience allows him to deliver highly personalised care across a wide range of health concerns, and he is known for his pragmatic, patient-focused approach. Dr Bennett values the diversity of general practice and enjoys supporting patients with everything from preventative health and screening through to complex, longer-term care.',
  },
  {
    name: 'Charles Levinson',
    organisation: 'Doctorcall',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Charles Levinson is the Founder and Medical Director of Doctorcall and has been one of the UK\'s leading home visiting GP specialists since 1989. Over more than three decades, he has combined clinical leadership with a highly personalised approach to patient care, shaped by warmth, discretion and continuity.',
    extendedBio: 'Charles is known for being thorough and unhurried, giving patients the time and reassurance they need. His long experience also brings the benefit of an extensive professional network, allowing him to arrange carefully judged specialist referrals and ensure each patient\'s care remains seamless, thoughtful and well coordinated.',
  },
  {
    name: 'Patrick Sheehan',
    organisation: 'Doctorcall',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Patrick Sheehan is a highly experienced private GP and home visiting specialist whose career combines broad hospital training with long-standing work in general practice. He is particularly valued by older patients for his reassuring manner, thoughtful clinical judgement and ability to see the wider picture of a patient\'s health',
    extendedBio: 'Patrick\'s approach is deeply personalised, with time taken to listen properly, assess carefully and provide clear, measured guidance. With many years of senior clinical experience behind him, he also brings a well-established network of trusted specialist contacts, helping to ensure that onward referrals are appropriate, well considered and tailored to the individual.',
  },
  {
    name: 'Santo Chakraborti',
    organisation: 'Doctorcall',
    category: 'gps-general-practice',
    specialty: 'GPs & General Practice',
    bio: 'Dr Santo Chakraborti is an experienced private GP with a strong background in home visiting care, combining broad hospital training with long-standing work in general practice.',
    extendedBio: 'His style of care is grounded in careful assessment, sound judgement and close attention to the individual needs of each patient. Alongside his broad clinical experience, he offers the added benefit of a long-established professional network, enabling him to make carefully chosen specialist referrals where needed and support patients with joined-up, thoughtful care beyond the initial consultation.',
  },
  {
    name: 'John O\'Dwyer',
    organisation: 'Mayo Clinic Healthcare London / HCA Healthcare',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'A consultant neurologist at The Mayo Clinic London and HCA\'s Lister Hospital, Dr John O\'Dwyer is an expert in holistic general neurology and medical care. Additionally, he has wide subspecialist knowledge, for complex disorders that need ongoing care.',
    extendedBio: 'Dr John O\'Dwyer is a senior consultant neurologist working at The Mayo Clinic London and The Lister Hospital (SW1W). His clinical interests - epilepsy, migraine and headache disorders, stroke and TIA, memory loss, Parkinson\'s disease and other movement disorders - sit at the heart of long-term neurological care. John is known for his careful, methodical assessments, his ability to translate complex investigations into clear guidance for patients and families, and his close collaboration with cardiology, psychiatry and rehabilitation teams. For anyone facing a new diagnosis or planning ongoing care for a loved one, he is a calm, authoritative presence who brings world-class expertise within reach',
  },
  {
    name: 'Ben Turner',
    organisation: 'HCA Healthcare UK',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'A senior consultant neurologist with HCA Healthcare UK at London Bridge and The Shard, Dr Ben Turner has a particular focus on neurological conditions that require sustained, multidisciplinary care, including Multiple Sclerosis Parkinson\'s disease and dementia.',
    extendedBio: 'Dr Ben Turner is a leading consultant neurologist practising within HCA Healthcare UK at London Bridge Hospital and The Shard for over 20 years. He has built a strong reputation for the assessment and long-term management of conditions that demand ongoing care - Multiple Sclerosis, Parkinson\'s disease, essential tremor, gait disturbance, memory disorders and the after-effects of stroke. Patients, families and care teams value his patient, methodical clinical style and his ability to coordinate ongoing care with neuro-rehabilitation, geriatric medicine and primary care, providing the integrated support that patients with chronic neurological disease so often need.',
  },
  {
    name: 'Emer MacSweeney',
    organisation: 'Re:Cognition Health',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'CEO and Medical Director of Re:Cognition Health, Dr Emer MacSweeney is a leading neuroradiologist and brain-health specialist at the forefront of memory and cognitive care.',
    extendedBio: 'Dr Emer MacSweeney founded Re:Cognition Health, and has built it into one of the UK\'s foremost private centres for the assessment and treatment of memory disorders, mild cognitive impairment and Alzheimer\'s disease - including access to leading clinical trials of disease-modifying therapies. For families noticing early changes in a loved one or supporting someone already living with dementia, Emer offers world-class diagnostic precision, clear guidance and a route into the most advanced treatments available, including Kisunla and leqembi, all delivered with vast experience and characteristic warmth and discretion.',
  },
  {
    name: 'Dominic Paviour',
    organisation: 'HCA Healthcare UK',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'A consultant neurologist who operates predominantly out of Welbeck Neurology. Dr Dominic Paviour specialises in Parkinson\'s disease and other movement disorders that require sustained, coordinated care.',
    extendedBio: 'Dr Dominic Paviour is a senior consultant neurologist. His specialist expertise in Parkinson\'s disease, dystonia, tremor and other movement disorders makes him particularly important for patients whose care arrangements depend on managing fluctuating symptoms over years. Dominic combines rigorous clinical assessment with a thoughtful, unhurried style - coordinating closely with primary care, geriatric medicine, neuro-rehabilitation and family carers to keep patients as well, as mobile and as independent as possible.',
  },
  {
    name: 'John Janssen',
    organisation: 'HCA Healthcare UK',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'A senior consultant neurologist with HCA Healthcare UK at Kings Road and Chiswick, Dr John Janssen brings calm authority and broad clinical experience to patients with neurological conditions requiring long-term care.',
    extendedBio: 'Dr John Janssen is a distinguished consultant neurologist working within HCA Healthcare UK. His extensive experience across the breadth of clinical neurology - stroke, headache, neurodegenerative disease, neuropathies - makes him a valued source of guidance for patients and families navigating difficult diagnoses. John is known for his methodical, accessible approach and his exceptional ability to coordinate care across specialists, primary care and the home, offering the steady, integrated medical oversight that complex neurological care so often requires.',
  },
  {
    name: 'Johnathan Chan',
    organisation: 'HCA Healthcare UK',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'Dr Chan is a highly qualified, London-trained consultant neurologist and dementia specialist with HCA Healthcare UK, who led the way in establishing London Bridge Hospital as one of the first centres in the UK to deliver the latest Amyloid Targeting Therapies for early Alzheimer\'s disease',
    extendedBio: 'Dr Chan led the way in establishing London Bridge Hospital as one of the first centres in the UK to deliver the latest Amyloid Targeting Therapies for the treatment of early Alzheimer\'s disease, giving patients new hope in combating this previously untreatable condition. Bringing together the most advanced diagnostic techniques in the field of memory and dementia assessment where he practises at The Shard, Dr Chan combines cutting-edge medicine with his bespoke, personalised and compassionate approach. He is known for his unique warmth and empathy, helping patients and their families find answers and navigate the complex challenges of this condition.',
  },
  {
    name: 'David Choluj',
    organisation: 'London Neurology Clinic',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'Dr David Choluj is the CEO and Medical Director of the London Neurology Clinic on Harley Street, in London\'s world-renowned medical district.',
    extendedBio: 'The London Neurology Clinic received the 2026 Neurology Practice Award from the American Academy of Neurology (AAN) - the world\'s largest professional organisation for neurologists - becoming the first clinic outside the United States to receive this prestigious distinction. Dr Choluj has gained extensive clinical experience at leading neurological centres, including Addenbrooke\'s Hospital in Cambridge, the Royal London Hospital, and the Royal Hospital for Neuro-disability in London. In addition to neurology, his expertise encompasses stroke medicine, neurological rehabilitation, and the management of complex neurological disabilities, with a strong emphasis on improving long-term patient outcomes and quality of life. He diagnoses and treats a wide range of neurological conditions, including headache disorders, dementia, epilepsy, stroke, multiple sclerosis, Parkinson\'s disease, and peripheral nerve disorders. He also has specialist expertise in the management of prolonged disorders of consciousness (PDOC), spasticity, cognitive disorders, and complex neurological disabilities. Known for his thorough, evidence-based, and patient-centred approach, Dr Choluj combines clinical excellence with multidisciplinary expertise to deliver highly personalised care tailored to each patient\'s individual needs.',
  },
  {
    name: 'Richard Perry',
    organisation: 'Cleveland Clinic London',
    category: 'neurology',
    specialty: 'Neurology',
    bio: 'Dr Richard Perry is a Consultant Neurologist with a specialist interest in memory disorders and dementias. He completed his medical degree at the medical college of St Bartholomew\'s Hospital in 1990.',
    extendedBio: 'Dr Perry\'s specialist experience in memory disorders and dementia was gained in Cambridge from 1995 to 1999 and in San Francisco from 1999 to 2000. He has been running memory clinics at Charing Cross Hospital in London since 2005 and specialises in early diagnosis and treatment of Alzheimer\'s disease and other dementias. He leads a team of clinicians running clinical trials for new cutting-edge treatments for dementias at Charing Cross Hospital and has pioneered the use of new diagnostic tests such as amyloid PET scans.',
  },
  {
    name: 'Daniel Krell',
    organisation: 'HCA Healthcare UK',
    category: 'oncology',
    specialty: 'Oncology',
    bio: 'A consultant medical oncologist at HCA\'s Wellington Hospital in St John\'s Wood, as well as the Harley Street Clinic, and Leaders in Oncology Care (Harley Street). Dr Daniel Krell is recognised for his compassionate, individualised approach to cancer care for patients with complex care needs.',
    extendedBio: 'He is known for tailoring treatment intensity to the realities of each patient - balancing efficacy against tolerability, comorbidity and quality of life - which is invaluable when cancer treatment must sit alongside ongoing care, frailty or other long-term conditions. Daniel is praised by families and care teams for his clarity, patience and willingness to spend the time needed at every step, from diagnosis through treatment planning to survivorship and palliative care, making him a trusted partner for any patient facing a cancer diagnosis whilst receiving care.',
  },
  {
    name: 'Alexandros Georgiou',
    organisation: 'HCA Healthcare UK',
    category: 'oncology',
    specialty: 'Oncology',
    bio: 'Dr Alex Georgiou is a Consultant Medical Oncologist at Guy\'s and St Thomas\' NHS Hospital (GSTT) and King\'s College Hospitals London, UK. His private practice is based at HCA London. He specialises in the treatment of thoracic malignancies: lung cancer, mesothelioma and thymic cancers. He is the UK chief investigator and principal investigator at GSTT in multiple international clinical trials investigating novel treatments for lung cancer and mesothelioma. He is also an honorary senior lecturer at King\'s College London (KCL) and leads on academic research at KCL and GSTT aiming to improve the early diagnosis, treatment, and outcomes for lung cancer patients.',
    extendedBio: 'Dr Georgiou currently serves as the clinical service lead for all Systemic Anti-Cancer Therapies (SACT) and the lung cancer and mesothelioma clinical trials lead at GSTT. He completed his medical oncology training at the Royal Marsden Hospital in London, 2012-2019. During his training he secured competitive Cancer Research UK (CRUK) funding, which supported his successful three-year PhD (2015-2018) at the Institute of Cancer Research (ICR) London. His doctoral research explored the mechanisms of resistance to targeted anti-cancer therapies, earning him a Merit award from the European Society of Medical Oncology Congress (ESMO) in 2018 and a University of London scholarship in 2019. He has an extensive publication record in oncology and in particular lung cancer and has been invited to speak at both national and international oncology conferences. Additionally, he provides clinical advice to \'EGFR Positive UK\', a UK lung cancer charity.',
  },
  {
    name: 'Nora Ng',
    organisation: 'Fortius Clinic',
    category: 'rheumatology',
    specialty: 'Rheumatology',
    bio: 'Dr Nora Ng is a top private Consultant Rheumatologist in London. Her NHS practice is at Guy\'s and St. Thomas\' Hospital, where she is part of the unique and comprehensive fibromyalgia clinic. She graduated from the University of Nottingham Medical School in 2003 and completed her subspecialist rheumatology training in London. During this time, she worked at numerous leading London teaching hospitals including Imperial College hospitals, The Royal London and University College Hospital.',
    extendedBio: 'She maintains a strong interest in research, especially in the area of ultrasound in inflammatory arthritis and has also undertaken an MD in this area. She has presented her research work at national and international conferences.',
  },
  {
    name: 'Prashanth Reddy',
    organisation: 'HCA Concierge',
    category: 'geriatric-medicine',
    specialty: 'Geriatric Medicine',
    bio: 'As a highly experienced consultant neuro-geriatrician, Dr Prashanth Reddy specialises in the holistic medical oversight of patients with complex, multi-layered care needs across The Lister Hospital and London Bridge.',
    extendedBio: 'Dr Prashanth Reddy is a consultant in geriatric medicine, with bases at The Lister Hospital and London Bridge. His practice is built around the needs of patients living with frailty, multiple long-term conditions, or significant cognitive change - comprehensive medical assessment, falls prevention, dementia and delirium care, polypharmacy review, continence, bone health and end-of-life planning. Prashanth is widely respected for his ability to see the whole person, working closely with families and professional carers to design realistic care plans that preserve independence and dignity. For any patient with multiple, interacting conditions, he is a natural and invaluable point of expert oversight.',
  },
  {
    name: 'Iñaki Bovill',
    organisation: 'HCA Healthcare UK',
    category: 'geriatric-medicine',
    specialty: 'Geriatric Medicine',
    bio: 'Dr Iñaki Bovill is a leading elderly care and general medicine doctor based in London. With over 25 years of experience, Dr Bovill is highly experienced in a wide range of treatments, with his areas of expertise including peri-operative medicine, continence, complex elderly medicine, rehabilitation, polypharmacy and geriatric medicine.',
    extendedBio: 'Dr Iñaki Bovill is a respected consultant in geriatric medicine practising across both NHS and private settings. His practice is built around the realities of caring for patients with multiple, interacting conditions - comprehensive assessment, falls and frailty management, dementia and delirium care, polypharmacy review and rehabilitation. Iñaki is valued for his attention to detail and his commitment to working closely with families, primary care and professional carers to design care plans that genuinely sustain quality of life at home.',
  },
  {
    name: 'Shahbaz Roshan',
    organisation: 'HCA Healthcare UK',
    category: 'geriatric-medicine',
    specialty: 'Geriatric Medicine',
    bio: 'A consultant in geriatric medicine, Dr Shahbaz Roshan takes a holistic, person-centred approach to clients living with frailty and multiple long-term conditions.',
    extendedBio: 'Dr Roshan is a respected consultant geriatrician based across multiple London hospitals. His practice is built around the medical realities of patients receiving care - managing frailty, falls, polypharmacy, cognitive change and the interplay of multiple chronic conditions. Shahbaz is particularly valued for his ability to address the physical and emotional dimensions of care together, working closely with families and professional carers to design realistic, dignity-preserving plans that hold up over time.',
  },
  {
    name: 'Shane Roche',
    organisation: 'Imperial College Healthcare NHS Trust',
    category: 'geriatric-medicine',
    specialty: 'Geriatric Medicine',
    bio: 'Dr Shane Roche has been a Consultant Physician with Imperial College Healthcare NHS Trust for 34 years. During this time, he has gained extensive experience across all aspects of general and geriatric medical care. He undertakes unselected acute medical on-call duties for three hospitals and runs general medicine, geriatric medicine, and falls clinics. He also carries out regular home visits, including visits to care, residential, and nursing homes. In addition, he is the Consultant responsible for the Harrow Rapid Response Team',
    extendedBio: 'Dr Roche has a specialist interest in the management of acute general and geriatric medicine, stroke, rehabilitation, Parkinson\'s disease, frailty, movement disorders, falls, and dementia. In recognition of his expertise and contribution to medicine, Dr Roche was featured in Tatler magazine in 2013 as one of the UK\'s Top 250 Consultants.',
  },
  {
    name: 'Prof. June Andrews OBE',
    organisation: 'Independent / National',
    category: 'dementia-specialist',
    specialty: 'Dementia Specialist',
    bio: 'One of the UK\'s most influential voices on dementia care, Prof. June Andrews OBE is an independent specialist whose practical guidance has shaped how families, professionals and care providers support people living with dementia.',
    extendedBio: 'Professor June Andrews OBE is a nationally recognised dementia specialist, author of Dementia: The One-Stop Guide and former director of the Dementia Services Development Centre at the University of Stirling. She advises families, care providers and institutions across the UK on every aspect of dementia - from early diagnosis and home adaptation to choosing care settings, briefing live-in carers, managing behavioural changes and navigating the legal and financial implications. June\'s independence, clarity and deep practical knowledge make her uniquely placed to help clients and families plan ahead, avoid common pitfalls and secure the best possible quality of life through the journey of dementia.',
  },
  {
    name: 'Vanash Patel',
    organisation: 'Private Practice',
    category: 'surgeons',
    specialty: 'Colorectal Surgeon',
    bio: 'Vanash Patel is a Consultant Colorectal and General Surgeon at West Hertfordshire Teaching Hospitals NHS Trust and an Honorary Clinical Associate Professor at Imperial College London.',
    extendedBio: 'He specialises in the management of colorectal cancer, benign colorectal conditions, abdominal wall hernias and advanced endoscopic disorders. He is recognised nationally for his work in robotic surgery, digital healthcare innovation and enhanced recovery pathways. Mr Patel leads one of the UK\'s highest-volume robotic colorectal surgery programmes and has pioneered integrated pathways combining robotic surgery, digital prehabilitation and virtual hospital care to improve patient outcomes and recovery. He has published extensively in colorectal surgery, robotic surgery and healthcare innovation, and is actively involved in research, education and service development. He supports adults requiring specialist colorectal and general surgical assessment, including patients seeking expert second opinions, management of colorectal cancer, diverticular disease, inflammatory bowel disease, pelvic floor disorders, hernias and complex benign colorectal conditions. He is committed to delivering highly personalised, patient-centred care using the latest evidence-based and minimally invasive techniques. Places of Work West Hertfordshire Teaching Hospitals NHS Trust (Watford General Hospital and St Albans City Hospital) Imperial College London (Honorary Clinical Associate Professor) Spire Bushey Hospital The Wellington Hospital Cleveland Clinic London',
  },
  {
    name: 'Lawrence Okiror',
    organisation: 'HCA Healthcare UK',
    category: 'surgeons',
    specialty: 'Consultant Thoracic and Robotic Surgeon',
    bio: 'Mr Lawrence Okiror is a consultant thoracic and robotic surgeon at London Bridge Hospital and The Lister Hospital, Chelsea, and leads the interventional airway service at Guy\'s and St Thomas\'',
    extendedBio: 'Alongside lung cancer and emphysema surgery, much of his work is relieving chest symptoms in older patients and advanced disease - breathlessness from fluid around the lung or a narrowed airway, pain, persistent cough - often through minor procedures under, including indwelling drains managed at home. He works alongside palliative-care and home-care teams, judges fitness for surgery on biology rather than birthdays, and says plainly when no procedure is the right answer. Enquiries from families are welcome.',
  },
  {
    name: 'Susan Alexander',
    organisation: 'Fortius Clinic',
    category: 'surgeons',
    specialty: 'Orthopaedic Surgeon',
    bio: 'Miss Susan Alexander is a Consultant Orthopaedic Shoulder Surgeon based at the Fortius Clinic in London, with over 30 years of experience in diagnosing and treating the whole range of shoulder conditions. She is currently President of the Independent Doctors Federation and is passionate about advocating for doctors in the independent sector with a focus on excellence in patient care.',
    extendedBio: 'Susan is known for her holistic approach to shoulder problems, recognising that every patient has different goals, priorities and circumstances, from elite athletes to those preferring a more sedentary lifestyle. She believes that surgery is the last option and takes the time to ensure patients feel heard, understood, and fully informed. By discussing all appropriate treatment options and their implications, she empowers patients to make the decisions that are right for them, placing them at the centre of every care plan. Her aim is not simply to treat a shoulder condition, but to help patients return to the activities, independence and quality of life that matter most to them.',
  },
  {
    name: 'Kshem Yapa',
    organisation: 'Imperial College Healthcare NHS Trust and Private practice',
    category: 'surgeons',
    specialty: 'Aesthetic & Plastic Surgeon',
    bio: 'Mr Kshem Yapa is a London-based Consultant Plastic Surgeon and deep plane facelift specialist, with a practice focused on advanced facial rejuvenation and natural-looking facial surgery. He is known for refined, elegant results that restore freshness, definition and facial harmony without creating an overdone or operated appearance.',
    extendedBio: 'His specialist areas of practice include the deep plane facelift, deep neck lift, lateral brow lift, lip lift, eyelid rejuvenation, facial fat grafting and adjunctive skin resurfacing. He also has a specialist interest in ultrasonic rhinoplasty, bringing the same principles of precision, balance and facial harmony to nasal surgery. Mr Yapa\'s philosophy is that excellent facial aesthetic surgery should be bespoke, anatomically precise and beautifully natural. His approach is grounded in a detailed understanding of facial anatomy, ageing and soft tissue behaviour, allowing him to tailor each procedure to the individual patient rather than offering a one-size-fits-all solution. Patients value his calm manner, honest advice and meticulous attention to detail, as well as his commitment to achieving results that look refreshed, elegant and believable. Mr Yapa graduated from the University of Cambridge and completed a PhD through Stanford University and King\'s College London. His doctoral research focused on the behaviour of adult stem cells in fat, reflecting a longstanding academic interest in tissue biology, healing and regenerative science. He developed an early interest in plastic surgery during placements at Harvard University and Massachusetts General Hospital in Boston, and has since undertaken further advanced training in London, Paris and the United States, with particular focus on modern facelift, neck lift and rhinoplasty techniques. He is a Fellow of the Royal College of Surgeons, FRCS (Plast), and is on the GMC Specialist Register for Plastic Surgery. He is also a member of BAAPS, BAPRAS, ISAPS and ASPS. Alongside private practice, Mr Yapa is a Consultant Plastic Surgeon at Imperial College Healthcare NHS Trust, where his reconstructive and trauma experience underpins his aesthetic work with precision, sound judgement and a strong commitment to patient safety. He has published more than 30 peer-reviewed articles and has received the Best Investigator Award at meetings of the American Society of Plastic Surgeons and the American Society of Maxillofacial Surgeons. Mr Yapa practises privately at The Lindo Wing, St Mary\'s Hospital, St John & St Elizabeth Hospital, and from his consulting rooms on Harley Street. He also featured in the Channel 4 documentary Emergency, which highlighted the work of plastic surgeons within London\'s major trauma network',
  },
  {
    name: 'Anthony Ghosh MBChB, MD, FRCS',
    organisation: 'The Spine MDT',
    category: 'surgeons',
    specialty: 'Spinal Neurosurgeon',
    bio: 'Anthony Ghosh is a consultant spinal neurosurgeon and a leading UK authority in spine care. He works with a wide network of leading clinicians, including physiotherapists, osteopaths, pain specialists, and rheumatologists, whom he leads to take full responsibility and help manage all the aspects of spine care. When surgery is required, he is highly trained in minimally invasive techniques.',
    extendedBio: 'He now solely practises privately out of 9 Harley Street and additional clinics in Kent and Essex. He is passionate about patient education through his highly popular YouTube channel, Anthony Ghosh, the UK Spine Guy.',
  },
  {
    name: 'Jan Herzog',
    organisation: 'Royal National Orthopaedic Hospital',
    category: 'surgeons',
    specialty: 'Spinal Surgeon',
    bio: 'Mr Jan Herzog is consultant orthopaedic and spinal surgeon with expertise in treating spinal conditions in both adults and children. He specialises in complex paediatric and adult spinal deformities, including scoliosis and kyphosis, as well as degenerative spine conditions.',
    extendedBio: 'Mr Herzog graduated from Humboldt University Berlin in 2004, before completing an MSc in diagnostic imaging at the University of Oxford. Following this, Mr Herzog began his surgical training in trauma and orthopaedics in Germany before being awarded a visiting fellowship at Massachusetts General Hospital, the teaching hospital to Harvard University in Boston/USA. After completing his training, Mr Herzog was appointed as a trauma and orthopaedic consultant at Charite in Berlin. There he developed his interest in spinal surgery. To pursue this interest, Mr Herzog moved to the UK and completed three spinal fellowships at Frimley Park Hospital, St George\'s Hospital and the Royal National Orthopaedic Hospital in Stanmore where he became a substantive consultant in 2019. Mr Herzog is known for his patient-focused approach, ensuring patients are fully informed and involved in decisions about their care. With his background in international rowing as both an athlete and team doctor, Mr Herzog has a particular interest in spinal conditions affecting athletes. He performs a wide range of spinal procedures including microdiscectomy, spinal decompression, spinal fusion, vertebroplasty, kyphoplasty and corrective surgery for scoliosis and kyphosis. Mr Herzog\'s practice is focused on delivering precise, evidence-based surgical care that puts an emphasis on improving function and quality of life. Alongside his clinical work Mr Herzog is actively involved in research into scoliosis, spinal myeloma and spinal navigation and robotics. He is on the GMC\'s specialist register for trauma and orthopaedic surgery and is a member of the British scoliosis Society and the "Deutsche Wirbelsaulengesellschaft".',
  },
  {
    name: 'Ryan Chin Taw Cheong BSc(Hons) MBBS AICSM MRCS(ENT) MSc FRCS(ORL-HNS)',
    organisation: 'Cleveland Clinic',
    category: 'ear-nose-throat',
    specialty: 'Ear, Nose and Throat',
    bio: 'Mr. Cheong practices at the Cleveland Clinic London and Welbeck Health Centre. He is a substantive Consultant ENT and Specialist Sleep Surgeon at the world leading Royal National ENT and Eastman Dental Hospitals, University College London Hospitals NHS Foundation Trust. He is currently the only Consultant ENT Surgeon in London and the UK with a full-time NHS practice exclusively in snoring and obstructive sleep apnoea',
    extendedBio: 'He is a multi-award-winning surgeon from prestigious institutions such as the Royal Society of Medicine, the Royal College of Surgeons of England, and the British Rhinological Society. He completed his extensive higher surgical training in the full breadth of ENT at world class institutions such as the Royal Marsden Hospital, Great Ormond Street Hospital, and the Royal London Hospital. Mr. Cheong successfully performed the first Genio Nyxoah hypoglossal nerve implants and the first female Inspire hypoglossal nerve implants for sleep apnoea in the UK, being the first surgeon in the UK to accomplish this he has been featured on the BBC, Sky News, The Guardian, The Times and other media outlets. He is the Founder and Director of the first International Sleep Surgery Course in the UK accredited by ENT-UK. He is also the first surgeon in the United Kingdom to have completed the Royal Society of Medicine Ellison-Cliffe Travelling Fellowship at the Stanford University Hospital Sleep Medicine Division and the Dowager Countess Eleanor Peel Trust Travelling Fellowship at the Asia Sleep Surgery Centre in Singapore. He has delivered more than 40 international and national academic presentations and published in high impact peer-reviewed journals such as the Lancet and JAMA. He is a regularly invited Key Note international speaker at scientific meetings. He has held multiple leadership positions in national ENT societies including the British Society of Facial Plastic Surgery. Mr. Cheong is passionate and committed to ensuring that every patient under his care receives world class personalized treatment options.',
  },
  {
    name: 'Professor Matthew Lechner',
    organisation: 'HCA The Shard and London Bridge',
    category: 'ear-nose-throat',
    specialty: 'Ear, Nose and Throat',
    bio: 'Prof Matt Lechner is a distinguished consultant rhinologist and ENT surgeon, specializing in a spectrum of nasal and sinus issues such as nasal blockage, rhinitis, sinusitis, smell loss, snoring, sleep apnea, and rhinoplasty surgery. Presently, he practices at HCA UK at the Shard and Canary Wharf. His comprehensive training in Ear, Nose & Throat surgery unfolded across prominent medical institutions in London, including University College London Hospital, Barts Health NHS Trust encompassing St Bartholomew\'s and the Royal London Hospital, Great Ormond Street Hospital, and The Royal National Throat, Nose and Ear Hospital.',
    extendedBio: 'Supplementing his general ENT training, he pursued a surgical Fellowship in Rhinology and Advanced Endoscopic Skull Base Surgery at Stanford University (Palo Alto, US). This endeavour equipped him with an extensive skill set in advanced endoscopic sinus surgery and nasal procedures. Beyond his surgical commitments, he actively participates in various clinical working groups, notably the Clinical Olfactory Working Group that focuses on olfactory (smell) disorders, including those associated with Covid-19. He was promoted from Associate Professor to Full Professor at University College London in 2024. At UCL, he leads a research program focused on rhinology, smell loss, early cancer drug development strategies, and precision medicine. His contribution to the medical field is evidenced by a wealth of publications, exceeding 180 original articles spanning rhinology, smell disorders, and tumour biology in diverse journals. He was awarded a prestigious Hunterian Professorship by the Royal College of Surgeons of England in 2020. His ardour for education is reflected in his international lectures, participation in courses, and involvement in teaching initiatives both in the UK and overseas. He was awarded the title \'Fellow of UK Higher Education Academy (FHEA)\' in 2013. Prof Lechner resides in London and nurtures interests in sports, philosophy, and the arts.',
  },
  {
    name: 'Sharon Heng, MBBS, PhD, Frcophth, FHEA',
    organisation: 'The London Clinic Eye Center and Moorfields Private',
    category: 'ophthalmology',
    specialty: 'Ophthalmology',
    bio: 'Ms Sharon Heng is a multi lingual consultant ophthalmic surgeon practicing privately at The London Clinic Eye Center and Moorfields Private. Her NHS practice at the world renowned Moorfields Eye Hospital. She is a specialist in medical retina diseases and the Clinical Lead of the Medical Retina Digital Clinics at Moorfields Eye Hospital and the Lead of the Northwest Diabetic Retinopathy Screening Program at Ealing Moorfields. Ms Heng has been practicing Ophthalmology in excess of 15 years. She is an expert in medical retina diseases, such as age related macular degeneration, diabetic retinopathy, cataracts and complex cataracts.',
    extendedBio: 'Ms Heng believes strongly in training the next generation of ophthalmologists and allied health professionals and is actively involved in developing teaching modules and programs for education within the NHS and beyond. She has travelled to China to assist in developing education programs for the local doctors. Ms Heng is also supervisor to several masters students at the Institute of Ophthalmology, UCL. She has also co-chaired several pan-london fellows and allied health professionals teaching courses. Other than teaching, Ms Heng is also active in research and is chief investigator of several clinical studies looking at equality within digital clinics and treatment in Age Related Macular Degeneration. Ms Heng is also contributor to a book that is now distributed to healthcare professionals in UK and Europe \'Biomarkers in Diabetic Macular Oedema\' Ms Heng practices personalised and precision medicine, utilizing advancements in imaging modality to tailor treatment suitable to individual patients. She ensures patients understands their disease and receives the best advice and bespoke short and longer term treatment plans tailored to their individual disease profile and needs. She speaks fluent English, Mandarin and understands Cantonese and Hokkien.',
  },
  {
    name: 'Robin D Hamilton MB BS, DM(dist), FRCOphth',
    organisation: 'Moorfields Eye Hospital',
    category: 'ophthalmology',
    specialty: 'Ophthalmology',
    bio: 'Mr Robin Hamilton is a Consultant Ophthalmologist in the Medical Retina and Cataract Services at Moorfields Eye Hospital, London. He received his medical degree from St Mary\'s Hospital, Paddington. He gained a Doctor of Medicine degree with distinction at Nottingham University. He performed his ophthalmic residency, Uveitis and Medical Retina fellowships at Moorfields eye hospital.',
    extendedBio: 'He is currently the Medical Director for Service and Transformation, having led the Medical Retina Department at Moorfields for 6 years. His main interests include novel therapies for treatment for Age related macular degeneration and diabetic retinopathy, in particular Anti-VEGF therapies and lasers. He has been involved in a number of trials examining these approaches and published over 100 peer reviewed articles. His surgical interests include standard and complicated cataract surgery with extended depth of focus and multifocal intraocular lenses. In over 20 years at Moorfields, with over 40 national and international trainees attending each year, he has numerous connections both nationally and internationally.',
  },
  {
    name: 'Sarah Alsawy-Davies',
    organisation: 'Auctoritas Advisory',
    category: 'psychiatry',
    specialty: 'Psychiatry',
    bio: 'Multi-award winning Dr Sarah Alsawy is a leading expert psychologist, specialising in the field of human relationships, re-wiring dynamics to create healthy and fulfilling interactions. With over 15 years of experience, her approaches create long- term changes that improve resilience, confidence, and wellbeing.',
    extendedBio: 'Dr Sarah Alsawy is a multi-award winning expert clinical psychologist, specialist in the field of relationships, family dynamics, and emotional resilience. Her Relational Alignment Protocol is an innovative, evidence-based framework that helps clients transform conflict, disconnection, and emotional distress into safety, trust, and wellbeing. With over 15 years of clinical experience, her clients experience strengthened relationships, improved communication, and increased confidence. Working with executive couples and families, her work is particularly important during significant life transitions, including marriage or separation, addition of new family members, succession planning, and liquidity events.',
  },
  {
    name: 'Sarah McIntyre',
    organisation: 'Private Practice',
    category: 'psychiatry',
    specialty: 'Psychiatry',
    bio: 'Dr Sarah McIntyre was recently sited in Psychology Today as, \'...one of London\'s most respected Psychotherapists.\' Her work in Existential Psychotherapy began at the University of Cambridge, where she was both a student and lecturer, focusing on the work of Freud and Heidegger.',
    extendedBio: 'Today Dr Sarah runs a successful practice in Sloane Square, where her commitment to solution-focused therapy, guarantees that clients get the results they are looking for. With a special interest in longevity, Sarah also works with men and women of all ages, to maximise health and wellbeing long past retirement. Other areas of work include relationship break-down and grief and anger management. Sara\'s work features on several podcasts and she continues to contribute to ongoing research in her field.',
  },
  {
    name: 'Donald Masi',
    organisation: 'Priory Healthcare',
    category: 'psychiatry',
    specialty: 'Psychiatry',
    bio: 'Dr Donald Masi is a general adult consultant psychiatrist and associate medical director at the Priory Hospital Roehampton. This is the largest private psychiatric hospital in the UK - supporting both inpatients and outpatients.',
    extendedBio: 'Dr Masi is also the lead clinician of The Residence. It is Priory Group\'s exclusive and flagship service, which offers bespoke inpatient psychiatric treatment and luxury. Dr Masi is known for his sensitive, supportive and effective management of people suffering with acute difficulties and longer-term psychiatric disability.',
  },
  {
    name: 'Jon Bowskill',
    organisation: '',
    category: 'exercise-rehab',
    specialty: 'Rehabilitation and Performance Consultant',
    bio: 'Jon is one of the UK\'s leading exercise and rehabilitation specialists. He has worked for many years within the medical community of London\'s West End and uses his background in human movement studies to provide exercise prescription and education based upon detailed individual assessments.',
    extendedBio: 'He couples this with providing lifestyle strategies and coaching support helping his clients to become stronger and more mobile allowing them to recover from painful problems and get back to doing more of what they love. For many years his area of specialist interest has been the use of movement, exercise and physical activity in the management of chronic spinal related problems.',
  },
  {
    name: 'Lucy Smith',
    organisation: 'Rehab Physio London',
    category: 'exercise-rehab',
    specialty: 'Physiotherapy',
    bio: 'Lucy is a co-founder and Co-Managing Director of Rehab Physio London, a specialist rehabilitation company delivering expert multidisciplinary therapy across a wide range of complex conditions. She is a neurological physiotherapist with over 20 years of clinical experience, having worked across NHS rehabilitation units and spent several years as a senior clinician in the acute neurological rehabilitation unit at The Wellington Hospital.',
    extendedBio: 'Intensive, multidisciplinary rehabilitation is at the heart of what Lucy does. She has built an in-house team of specialist therapists including occupational therapists, speech and language therapists, neuropsychologists and rehabilitation assistants, who work together to create bespoke programmes around each client\'s individual goals. For Lucy, rehabilitation has always been about more than meeting basic functional needs; it\'s about helping people get back to the life they want to live. The team works primarily in clients\' own homes, providing a discreet and fully tailored service, and Lucy has long been a believer in the power of non-medicalised environments to support recovery. This thinking led her to develop Rehab Escapes, RPL\'s residential rehabilitation intensive in the Cotswolds, where clients benefit from expert therapy alongside the restorative qualities of beautiful countryside and community. Internationally, Lucy and her team have delivered rehabilitation programmes across Central and South America, Switzerland, Africa and the Caribbean, and have worked aboard private yachts in the South of France, supporting clients to keep living their lives whilst continuing their recovery.',
  },
  {
    name: 'Natasha Price MCSP',
    organisation: 'Central Health Physio',
    category: 'exercise-rehab',
    specialty: 'Physiotherapy',
    bio: 'Founded in 1994 by Natasha Price as Chancery Lane Physiotherapy, the practice has grown steadily, rebranding as Central Health Physiotherapy in 2005 to reflect its expanding reach and expertise. What began as a commitment to providing exceptional local care has evolved into one of London\'s leading physiotherapy networks, with expert clinicians working across multiple clinics. The team provides specialist physiotherapy for people of all ages and a wide range of conditions, helping patients regain mobility, independence, and confidence.',
    extendedBio: 'Central Health Physiotherapy is trusted by many of London\'s leading surgeons, consultants, and healthcare professionals. Whether someone is recovering from illness, a hip fracture, stroke, surgery, or another condition, the team offers expert rehabilitation either in the comfort of the patient\'s home or at one of its welcoming clinics.',
  },
  {
    name: 'Ali Yeo',
    organisation: 'Six Physio',
    category: 'exercise-rehab',
    specialty: 'Physiotherapy',
    bio: 'Ms Ali Yeo, a clinical specialist physiotherapist at Six Physio, brings over 20 years of experience to treating a diverse range of musculoskeletal conditions. Driven by a philosophy where science meets soul, she is dedicated to her well-known passion for keeping people active, whether they need an operation, have slowed down, been injured or are looking at their longevity, Ali joined Six Physio to launch their bespoke treatment service, offering expert care at homes, offices, gyms, hotels, or even on the padel court.',
    extendedBio: 'This initiative to see people in their own environment empowers patients to select their preferred treatment location at any stage of their recovery. With a focus on orthopedic, vestibular, and complex musculoskeletal health - alongside neurological support for conditions like Parkinson\'s - Ali has curated an elite team of physiotherapists who share her unwavering commitment to clinical success. Six at Home operates within London\'s most prestigious enclaves, including Chelsea, Fulham, and Fitzrovia, Wandsworth and Wimbledon as well as the medical hubs of Mayfair and Knightsbridge. Renowned for their discretion and expertise, Ali and her team provide bespoke, high-end physiotherapy treatment within the privacy of a patient\'s residence. By collaborating seamlessly with medical consultants, they ensure a sophisticated and integrated recovery journey where medical science meets personalized excellence.',
  },
  {
    name: 'Zoe Wyrko',
    organisation: 'Riverstone Living',
    category: 'residential',
    specialty: 'Retirement Living',
    bio: 'An experienced Geriatrician, Dr Zoe Wyrko is now Wellbeing and Quality Director at Riverstone Living, London\'s luxury retirement living operator.',
    extendedBio: 'Riverstone knows that health is wealth, approached with intelligence, discretion and choice. Expect personalised wellbeing support, including a dedicated health concierge, programmes designed for brain and physical strength, and access to a private GP. Live well for longer, on your terms.',
  },
  {
    name: 'Nuno Santos Lopes',
    organisation: 'KYN',
    category: 'residential',
    specialty: 'Care and Nursing Homes',
    bio: 'Mr Nuno Santos Lopes is the Director of Care and Home Manager for KYN Hurlingham, which provides residential, nursing and respite care in Fulham. Nuno is known for his belief that great care starts with human connection. Throughout his career, he has championed dignity, compassion, teamwork and continuous learning, always striving to make a positive difference in the lives of residents, families and care professionals alike. He leads an exceptional in-house team of 24/7 carers and nurses, with physio services, and an elevated approach to holistic wellbeing and cultured life enrichment at KYN Hurlingham',
    extendedBio: 'With a background in palliative care, dementia care and care home leadership, he has built a reputation for creating cultures where residents, families and colleagues feel supported, respected and empowered. He is particularly passionate about education, research and sharing best practice across the care sector, having led international programmes connecting care professionals in more than 20 countries.',
  },
];
